name: Larave CI

on: [push]

jobs:
    laravel-test:
        runs-on: ubuntu-latest 
        
        services:
            mysql:
                image: mysql:8.0
                ports:
                    - 3006:3006
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL DATABASE: laravel
        
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set Up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
            extentions: mbstring, bemath, pdo, pdo_mysql

        - name: Isntall packages
          run: composer install --no-interaction

        - name: Set App 
          run: cp .env.example .env
            
        - name: Set Key
          run: php artisan key:generate
            
        - name: Run test
          id: test
          run: vendor/bin/phpunit

        - name: Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: artifacts
            path: composer.json

        - name: deploy
          if: steps.test.outcome == 'success'
          run: ls